version: "3"
services:
  demo:
    build:
      dockerfile: Dockerfile
    image: demo
    ports:
    - 8080:8080
    depends_on:
      - redis
  redis:
    image: redis:last
    ports:
    - 6379:6379